package plugin:general;

interface logging {
    debug: func(message: string);
    info: func(message: string);
    warn: func(message: string);
    error: func(message: string);
}

interface config {
    config-get: func(path: string) -> string;
    config-delete: func(path: string);
}

world general {
    import logging;
    import config;
    export init: func();
}
